name: intrusion-detector-pipeline

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pip:
      - dvc==2.45.1
      - dvc[s3]==2.45.1
      - dvclive==2.1.0
      - gto==0.2.7
      - pandas==1.5.3
      - scikit-learn==1.2.1
      - matplotlib==3.7.0
      - imbalanced-learn==0.10.1
      - joblib===1.2.0