name: Retrain Pipeline
on:
# trigger that allows you to manually trigger a GitHub Action, without having to push or create a pull request
  workflow_dispatch:
    inputs:
      path_to_data_file:
        description: 'Path to new data file'
        required: true
        type: string

jobs:
  run_code:
    name: Update training data
    runs-on: ubuntu-latest

    # this permission is required by the git-auto-commit-action
    permissions:
      contents: write

    steps:
      # checks out the code of the branch
      - uses: actions/checkout@v2
      # sets up the conda environment
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: dvc-intrusion-detector-pipeline
          environment-file: conda.yaml
          auto-activate-base: false
          miniconda-version: "latest"

      # pulls all the data from DVC
      - name: Pull data from DVC
        # we need to set this shell config on every step we use conda or it wont work
        shell: bash -l {0} 
        run: |
          dvc remote modify storage --local access_key_id ${{ secrets.aws_access_key_id }}
          dvc remote modify storage --local secret_access_key ${{ secrets.aws_secret_access_key }}
          # pulls all the files
          dvc pull

      - name: Updates the training data
        shell: bash -l {0}
        run: |
          aws s3api get-object --bucket s3://${{ secrets.RETRAIN_AWS_BUCKET }} --key ${{ inputs.path_to_data_file }} data/data.csv
          dvc add data/data.csv

      # executes the pipeline
      - name: Run the pipeline with DVC
        shell: bash -l {0}
        run: |
          dvc repro

      # pushes new / changes data files to DVC
      - name: Push the outcomes to DVC remote storage 
        shell: bash -l {0}
        run: dvc push
      
      # If there are any changes we commit and push them
      - name: Commit changes to the retrain branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit changes in dvc.lock
          branch: retrain